// categories
export { default as BasketballIcon } from './basketball.svg'
export { default as MagicWandIcon } from './magic-wand.svg'
export { default as MusicNotesIcon } from './music-notes.svg'
export { default as PaintBrushIcon } from './paint-brush.svg'
export { default as PlanetIcon } from './planet.svg'
export { default as SwatchesIcon } from './swatches.svg'
export { default as VideoCameraIcon } from './video-camera.svg'
export { default as CameraIcon } from './сamera.svg'

export { default as DiscordIcon } from './discord.svg'
export { default as EnvelopeIcon } from './envelope.svg'
export { default as EyePurpleIcon } from './eye-purple.svg'
export { default as EyeIcon } from './eye.svg'
export { default as InstagramIcon } from './instagram.svg'
export { default as LogoIcon } from './logo.svg'
export { default as RocketLaunchIcon } from './rocket-launch.svg'
export { default as TwitterIcon } from './twitter.svg'
export { default as UserIcon } from './user.svg'
export { default as YoutubeIcon } from './youtube.svg'
export { default as InternetIcon } from './internet.svg'
